"""
claude_runner.py — sends extraction report to Claude API and parses response.
"""

import os
import re
import datetime
import anthropic

from constitution_compressed import CONSTITUTION

MODEL    = "claude-sonnet-4-6"
MAX_TOKENS = 4000


def run_council_session(extraction_report: str) -> tuple[str, str]:
    """
    Send the extraction report to Claude with the compressed constitution as system prompt.
    Returns (full_report, telegram_summary).
    Raises RuntimeError on API failure.
    """
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    today_str = datetime.date.today().strftime("%d-%b-%Y")

    user_message = f"""{extraction_report}

---

INSTRUCTION TO COUNCIL:

The Section 0 Data Extraction Report above has been automatically generated by the pipeline.
Section 0 is already complete — do not re-extract data.

Please run the Council framework in Standard Mode beginning from Section 1 (Input Validation Report)
and proceeding through all sections up to and including Section 13 (Journal Entry).

Follow the Constitution exactly:
- All sections 1 through 13 must be present and complete.
- All 8 agents must participate as defined.
- Cross-examination must occur (Section 5).
- Execution vote must occur (Section 11).
- Final Council Verdict must be produced (Section 12).
- Journal Entry must be produced (Section 13).

Note: This is an automated session. Event Calendar, Macro Notes, FII/DII Flows, and Sector Heatmap
are not available. Agent 3 must use the three-pillar format and declare inputs unavailable
for those pillars. This is expected and does not block the session.

DTE ALERT: If DTE classification is Near Expiry (DTE ≤ 3), flag this prominently in Sections 1, 10,
and 12. Apply all Near Expiry governance: 50% size reduction, 70% profit harvest threshold,
caution on new entry.

After Section 13, end your response with the TELEGRAM SUMMARY section in the exact format
specified in the Constitution. This section is mandatory and must be the final content of your response.

Today's date: {today_str}
"""

    try:
        response = client.messages.create(
            model=MODEL,
            max_tokens=MAX_TOKENS,
            system=CONSTITUTION,
            messages=[{"role": "user", "content": user_message}],
        )
    except anthropic.APIError as e:
        raise RuntimeError(f"Claude API error: {e}") from e

    full_report = response.content[0].text

    telegram_summary = _extract_telegram_summary(full_report)

    return full_report, telegram_summary


def _extract_telegram_summary(text: str) -> str:
    """
    Extract the TELEGRAM SUMMARY block from the full Council response.
    Returns the summary text, or a fallback error message if not found.
    """
    # Match from "TELEGRAM SUMMARY" heading to end of text
    pattern = r"(?:={10,}\s*\n)?TELEGRAM SUMMARY\s*(?:\n={10,})?\s*\n([\s\S]+?)(?:={10,}\s*$|$)"
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        return match.group(1).strip()

    # Fallback: look for the BIAS: field as the start
    bias_match = re.search(r"(BIAS:[\s\S]+)", text, re.IGNORECASE)
    if bias_match:
        return bias_match.group(1).strip()

    return "TELEGRAM SUMMARY not found in Council response. Check full report."


def save_full_report(full_report: str) -> str:
    """
    Save the full Council report to a dated .txt file.
    Returns the file path.
    """
    date_str  = datetime.date.today().strftime("%Y-%m-%d")
    filename  = f"Council_{date_str}.txt"
    # Save in the same directory as this script
    filepath  = os.path.join(os.path.dirname(__file__), filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(full_report)
    print(f"Full report saved: {filepath}")
    return filepath
